// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bot-engine/db"
	"bot-engine/handlers"
	"bot-engine/repositories"
	"bot-engine/routes"
	"bot-engine/services"
	middleware "di/middlewares"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitializeAPI(client *mongo.Client) (*gin.Engine, error) {
	database := db.NewMongoDatabase(client)
	repositoriesRepositories := repositories.NewRepositories(database)
	servicesServices := services.NewServices(repositoriesRepositories)
	handlersHandlers := handlers.NewHandler(servicesServices)
	middlerware := middleware.NewMiddlerware()
	engine := routes.NewRouter(handlersHandlers, middlerware)
	return engine, nil
}
