// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bot-engine/config"
	"bot-engine/db"
	"bot-engine/handlers"
	"bot-engine/middlewares"
	"bot-engine/repositories"
	"bot-engine/routes"
	"bot-engine/services"
	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitializeAPI(client *mongo.Client) (*gin.Engine, error) {
	database := db.NewMongoDatabase(client)
	repositoriesRepositories := repositories.NewRepositories(database)
	secretsConfig, err := config.NewSecretsConfig()
	if err != nil {
		return nil, err
	}
	botSecretsConfig := config.ProvideBotSecrets(secretsConfig)
	authSecretsConfig := config.ProvideJWTSecrets(secretsConfig)
	servicesServices := services.NewServices(repositoriesRepositories, botSecretsConfig, authSecretsConfig)
	handlersHandlers := handlers.NewHandler(servicesServices)
	middlewares := middleware.NewMiddlewares(authSecretsConfig)
	engine := routes.NewRouter(handlersHandlers, middlewares)
	return engine, nil
}
